name: Tests

on: [push]

jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        python-version: [ "3.10" ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run pytest
        run: |
          python -m pytest tests/

  publish-to-test-pypi:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs: tests

    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
        python-version: [ "3.9" ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Publish to PyPI
        run: |
          poetry version $(git describe --tags --abbrev=0)
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi ${{ secrets.TEST_PYPI_TOKEN }}
          poetry publish -r test-pypi --build
